apiVersion: v1
kind: List
metadata:
  name: openshift-audit-pipeline
items:

# Configure our Docker image repository
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: openshift-audit
    labels:
      app: openshift-audit

# Configure our build pipeline template
- apiVersion: v1
  kind: Template
  metadata:
    name: openshift-audit-pipeline
  parameters:
  - name: GIT_REPO
    description: Source repository
    value: https://github.com/raizv/openshift-audit.git
  - name: GIT_BRANCH
    description: Branch to build from
    value: master
  objects:

  # # Configures the OpenShift/Jenkins build pipeline
  # - apiVersion: v1
  #   kind: BuildConfig
  #   metadata:
  #     name: openshift-audit-pipeline
  #     labels:
  #       app: openshift-audit
  #   spec:
  #     source:
  #       type: Git
  #       git:
  #         uri: ${GIT_REPO}
  #         ref: ${GIT_BRANCH}
  #       sourceSecret:
  #         name: github-secret
  #     triggers:
  #       - type: GitHub
  #         github:
  #           secret: supersectet
  #     runPolicy: SerialLatestOnly
  #     strategy:
  #       type: JenkinsPipeline
  #       jenkinsPipelineStrategy:
  #         jenkinsfilePath: Jenkinsfile

  # Configure our Docker container build
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: openshift-audit
      labels:
        app: openshift-audit
    spec:
      source:
        type: Git
        git:
          uri: ${GIT_REPO}
          ref: ${GIT_BRANCH}
        # sourceSecret:
        #   name: github-secret
        # secrets:
        #   - secret:
        #       name: secret
        runPolicy: SerialLatestOnly
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: openshift-audit:latest

